<?php
/*********************************************************************************
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if ($this->orgTree->getSize() != 0) { ?>

    <style>
        #ifrDiv {
            z-index: 1000;
            position: absolute;
            border: 1px solid red;
            top: 200px;
            left: 200px;
        }

        .jOrgChart .node .deptclass {
            background-color: red !important;
        }
    </style>
    <div id="grayout"></div>

    <ul id="org" style="display:none;">
        <?php echo $this->controller->renderTree($this->orgTree) ?>
    </ul>

    <script type='text/javascript'>
        jQuery(document).ready(function () {
            $('#grayout').slimScrollHorizontal({
                alwaysVisible: false,
                start: 'left',
                position: 'bottom',

            }).css({background: '#ccc', paddingBottom: '10px'});
            $("div.node").each(function () {
                var text = $(this).text();
                text = $.trim(text);
                var subtext = text.substring(0, 30);
                $(this).html(subtext);
                $(this).attr("title", $.trim(text));
            });
            $("#org").jOrgChart();
        });

    </script>

<?php } else { ?>
    <div class="ml-alert-1-info m1-info-set">
        <div class="style-1-icon info"></div>
        Organization Information is not added yet.
    </div>
<?php } ?>